version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db_fastapi
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    ports:
      - "5434:5432"
  web:
    build: .
    container_name: shots_url_fastapi
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./src/.env
    command: sh -c "alembic upgrade head && python main.py"
    depends_on:
      - db

volumes:
  postgres_data: