"""02_delete_url

Revision ID: 03b59e804325
Revises: d8745e0a41ea
Create Date: 2023-01-24 17:04:18.361015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b59e804325'
down_revision = 'd8745e0a41ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shorts', sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shorts', 'deleted')
    # ### end Alembic commands ###
